config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :playlists
  resources :musics

  get "/player", to: "musics#player_viewer", as: "player_viewer"

  root to: "playlists#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
# frozen_string_literal: true

class Music < ApplicationRecord
  enum status: [:waiting, :done, :processing, :downloading, :aborted]
  after_commit :set_music, on: [:create]

  has_many :playlist_musics, dependent: :destroy
  has_many :playlists, through: :playlist_musics

  has_one_attached :mp3
  has_one_attached :thumbnail

  # has_one :thumbnail, -> { where(name: 'image') }, class_name: "ActiveStorage::Attachment", as: :record, inverse_of: :record, dependent: false
  # has_one :thumbnail_blob, through: :image_attachment", class_name: "ActiveStorage::Blob", source: :blob

  def set_music
    MusicDownloadJob.perform_later(self)
  end
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  enum status: [:waiting, :done, :processing, :aborted]

  has_many :playlist_musics
  has_many :musics, through: :playlist_musics
  has_one_attached :thumbnail

  after_commit :set_playlist, on: [:create]

  def set_playlist
    PlaylistSetupJob.perform_later self
  end
end

app/models/playlist_music.rb
# frozen_string_literal: true

class PlaylistMusic < ApplicationRecord
  belongs_to :playlist
  belongs_to :music
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
# frozen_string_literal: true

class MusicsController < ApplicationController
  before_action :set_music, only: %i[show edit update destroy]

  def player_viewer
    @music = session[:player][:music] if session[:player]
  end

  # GET /musics or /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1 or /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics or /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: "Music was successfully created." }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1 or /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: "Music was successfully updated." }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1 or /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: "Music was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_music
    @music = Music.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def music_params
    params.require(:music).permit(:title, :link, :start, :end, :thumbnail, :duration, :artist)
  end
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[show edit update destroy]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
    @musics = @playlist.musics.order(:id).with_attached_thumbnail.strict_loading.first(20)
    # @playlist = Playlist.eager_load(musics: {thumbnail_attachment: :blob}).find(params[:id])
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def playlist_params
    params.require(:playlist).permit(:title, :thumbnail, :code)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/musics_helper.rb
# frozen_string_literal: true

module MusicsHelper
end

app/helpers/playlists_helper.rb
# frozen_string_literal: true

module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sytb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-beaver-900 text-white">
    <div class="container max-w-4xl mx-auto mb-20 px-4">
      <%= yield %>
    </div>
    <%= render Player::Component.new %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music) do |form| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%# <%= form.text_field :thumbnail %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.text_field :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.text_field :end %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musics</h1>

<%= render TestComponent.new %>

<a href="#"
  data-reflex="click->Counter#increment"
  data-step="1" 
  data-count="<%= @count.to_i %>"
  >Increment <%= @count.to_i %></a>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Thumbnail</th>
      <th>Duration</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.title %></td>
        <td><%= music.link %></td>
        <td><%= music.thumbnail %></td>
        <td><%= music.duration %></td>
        <td><%= music.artist %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Back', musics_path %>

app/views/musics/player_viewer.html.erb
<div id="player_viewer">
  <%= render Musics::Viewer::Component.new(music: @music) %>
</div>

app/views/musics/show.html.erb
xD

app/views/playlists/_form.html.erb
<%= simple_form_for(playlist) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :code %>
  <%= f.input :thumbnail %>

  <div class="text-right">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="block text-center mt-4 mb-10 text-3xl">
  Playlists
</div>

<% @playlists.each do |playlist| %>
  <%= render Playlists::Card::Component.new(playlist: playlist) %>
<% end %>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<div class="flex items-center text-center justify-center text-2xl mt-4 mb-10">
  <%= @playlist.title %>
</div>

<div class="-mx-4">
  <%= render Musics::List::Component.new(musics: @musics, playlist: @playlist) %>
</div>